version: '3'
services:
  cloudcsv-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./etc/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    networks:
      - traefik-network

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_EXPOSED_PORT}:8080

  cloudcsv-api:
    image: php:7.2-apache
    build: .
    depends_on:
      - cloudcsv-db
    labels: 
      - "traefik.http.routers.cloudcsv-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.cloudcsv-api.entrypoints=websecure"
      - "traefik.http.routers.cloudcsv-api.tls.certresolver=myresolver"
    networks:
      - traefik-network

networks:
  traefik-network:
    external:
      name: traefik_proxynet

volumes:
  mysqldata: